name = "decap-auth-ruabien"
main = "src/index.ts"
compatibility_date = "2024-05-02"

[vars]
# Không cần điền ID/Secret ở đây, chúng ta điền ở mục Settings trên Cloudflare bảo mật hơn.

[site]
bucket = ""
account_id = "86aaf62d7a969bfa28b1151beb67a7d9"
